# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seongdokim/Projects/SeongdoKim/RemoteCameraViewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seongdokim/Projects/SeongdoKim/RemoteCameraViewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seongdokim/Projects/SeongdoKim/RemoteCameraViewer/CMakeFiles /home/seongdokim/Projects/SeongdoKim/RemoteCameraViewer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seongdokim/Projects/SeongdoKim/RemoteCameraViewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RemoteCameraViewer

# Build rule for target.
RemoteCameraViewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RemoteCameraViewer
.PHONY : RemoteCameraViewer

# fast build rule for target.
RemoteCameraViewer/fast:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/build
.PHONY : RemoteCameraViewer/fast

RemoteCameraViewer.o: RemoteCameraViewer.cpp.o

.PHONY : RemoteCameraViewer.o

# target to build an object file
RemoteCameraViewer.cpp.o:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/RemoteCameraViewer.cpp.o
.PHONY : RemoteCameraViewer.cpp.o

RemoteCameraViewer.i: RemoteCameraViewer.cpp.i

.PHONY : RemoteCameraViewer.i

# target to preprocess a source file
RemoteCameraViewer.cpp.i:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/RemoteCameraViewer.cpp.i
.PHONY : RemoteCameraViewer.cpp.i

RemoteCameraViewer.s: RemoteCameraViewer.cpp.s

.PHONY : RemoteCameraViewer.s

# target to generate assembly for a file
RemoteCameraViewer.cpp.s:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/RemoteCameraViewer.cpp.s
.PHONY : RemoteCameraViewer.cpp.s

RemoteViewer.o: RemoteViewer.cpp.o

.PHONY : RemoteViewer.o

# target to build an object file
RemoteViewer.cpp.o:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/RemoteViewer.cpp.o
.PHONY : RemoteViewer.cpp.o

RemoteViewer.i: RemoteViewer.cpp.i

.PHONY : RemoteViewer.i

# target to preprocess a source file
RemoteViewer.cpp.i:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/RemoteViewer.cpp.i
.PHONY : RemoteViewer.cpp.i

RemoteViewer.s: RemoteViewer.cpp.s

.PHONY : RemoteViewer.s

# target to generate assembly for a file
RemoteViewer.cpp.s:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/RemoteViewer.cpp.s
.PHONY : RemoteViewer.cpp.s

utilities.o: utilities.cpp.o

.PHONY : utilities.o

# target to build an object file
utilities.cpp.o:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/utilities.cpp.o
.PHONY : utilities.cpp.o

utilities.i: utilities.cpp.i

.PHONY : utilities.i

# target to preprocess a source file
utilities.cpp.i:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/utilities.cpp.i
.PHONY : utilities.cpp.i

utilities.s: utilities.cpp.s

.PHONY : utilities.s

# target to generate assembly for a file
utilities.cpp.s:
	$(MAKE) -f CMakeFiles/RemoteCameraViewer.dir/build.make CMakeFiles/RemoteCameraViewer.dir/utilities.cpp.s
.PHONY : utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... RemoteCameraViewer"
	@echo "... RemoteCameraViewer.o"
	@echo "... RemoteCameraViewer.i"
	@echo "... RemoteCameraViewer.s"
	@echo "... RemoteViewer.o"
	@echo "... RemoteViewer.i"
	@echo "... RemoteViewer.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

